### ISSUE TITLE
Skrypt zwraca informację o powodzeniu instalacji nawet gdy nie uda się ona. 

### ISSUE THREAD

**Issue by nibexo** [nolt/skrypt-epity#1]
Posiadam Ubuntu 16.10 x64 i gdy próbowałem zainstalować program epity, instalacja nie powiodła się. Jednak skrypt wypisał informację, że wszystko zakończyło się pozytywnie.

> Sprawdzimy jaką dystrybucję oraz architekturę systemu Linux posiadasz(obsługiwane Debian i Ubuntu)
> Ubuntu x86_64
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Package libnss3-1d:i386 is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'libnss3-1d:i386' has no installation candidate
> E: Unable to locate package lib32nss-mdns
> Będę instalował pobrane aplikacje!
> /tmp/air.NJqAl4/setup: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
> sudo: /usr/bin/Adobe AIR Application Installer: command not found
> --- Gratulacje, wszystko poszło pięknie i gładko. Folder z plikami instalacyjnymi nie jest już potrzebny, mogę go usunąć za Ciebie :) (t/n)? ---

**Comment by nolt** [comment]
Niestety pakiet został wyrzucony z repozytorium Ubuntu 16.10. Instalacja w tym przypadku jest nie możliwa.

**Comment by nolt** [comment]
Na dniach zaktualizuję skrypt, aktualnie testowałem i aplikacja działa. Nie trzeba będzie instalować wielu pakietów tylko jeden.

**Comment by nolt** [comment]
Skrypt został zaktualizowany.
